/* tslint:disable */
export const memory: WebAssembly.Memory;
export function __wbindgen_global_argument_ptr(): number;
export function __wbg_tetrisboard_free(a: number): void;
export function tetrisboard_new(): number;
export function tetrisboard_get_width(a: number): number;
export function tetrisboard_get_score(a: number): number;
export function tetrisboard_get_game_over(a: number): number;
export function tetrisboard_set_game_over(a: number): void;
export function tetrisboard_get_generate_new_shape(a: number): number;
export function tetrisboard_set_generate_new_shape(a: number): void;
export function tetrisboard_get_height(a: number): number;
export function tetrisboard_get_space_used(a: number): number;
export function tetrisboard_get_space_length(a: number): number;
export function tetrisboard_check_shape_is_out_of_bounds(a: number, b: number): void;
export function tetrisboard_check_collision(a: number, b: number): number;
export function tetrisboard_check_for_completed_row(a: number): void;
export function tetrisboard_add_shape_to_space_used(a: number, b: number): void;
export function tetrisboard_get_shape_position(a: number, b: number): void;
export function tetrisboard_update_shape_position(a: number, b: number): void;
export function tetrisboard_move_shape_down(a: number, b: number): void;
export function tetrisboard_move_shape_right(a: number, b: number): void;
export function tetrisboard_move_shape_left(a: number, b: number): void;
export function tetrisboard_render(a: number, b: number): void;
export function __wbg_tetromino_free(a: number): void;
export function tetromino_generate_random_shape(a: number): number;
export function tetromino_new_reverse_step_shape(): number;
export function tetromino_new_step_shape(): number;
export function tetromino_new_leg_shape(): number;
export function tetromino_new_reverse_leg_shape(): number;
export function tetromino_new_square_shape(): number;
export function tetromino_new_bar_shape(): number;
export function tetromino_new_hat_shape(): number;
export function tetromino_get_block_size(a: number): number;
export function tetromino_get_block1(a: number): number;
export function tetromino_get_block2(a: number): number;
export function tetromino_get_block3(a: number): number;
export function tetromino_get_block4(a: number): number;
export function tetromino_move_shape_down(a: number, b: number): void;
export function tetromino_move_shape_right(a: number): void;
export function tetromino_move_shape_left(a: number): void;
export function tetromino_transform_shape(a: number, b: number): void;
export function tetromino_transform_bar(a: number, b: number): void;
export function tetromino_transform_step(a: number, b: number): void;
export function tetromino_transform_reverse_step(a: number, b: number): void;
export function tetromino_transform_hat(a: number, b: number): void;
export function tetromino_transform_leg(a: number, b: number): void;
export function tetromino_transform_reverse_leg(a: number, b: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_free(a: number, b: number): void;
